version: "3"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network: